### ISSUE TITLE
Auth-Plugin not working with twitch.tv

### ISSUE THREAD

**Issue by joekinley** [gdamjan/erlang-irc-bot#54]
The ircbot does not work out of the box when used as a bot on twitch.tv irc channels. The authorization from the plugin comes too late, as their IRC server apparently works differently than the main bot.

It works when you do it in the ircbot_fsm.erl:send_login/2 function. If you add the PASS with the password there it works. 

I have yet to figure out how to properly fix this.

**Comment by gdamjan** [comment]
Do they have it documented somewhere how it works for them?

**Comment by joekinley** [comment]
Not really. I found it out by wading through the raw IRC output. I can do it later today and paste my findings here so you get an idea.

**Comment by gdamjan** [comment]
ok. also, it would be interesting to investigate alternative ways of authentication. Nickserv always looked fragile.

**Comment by joekinley** [comment]
Well as the setup only allows for one connection, therefore only one user, it would be enough in my opinion to have the password at the settings itself, and do the authentication at the start, like twitch servers do it, which should also work with all the other servers. 
So in the ircbot_fsm:send_login/2 we need to add the line: 
send(Conn, ["PASS ", Password]),

If the password is present. This worked with my setup, just that I added the password directly, as I didn't have time to figure out how to properly pass it from the settings to that function

**Comment by gdamjan** [comment]
ok. I think I can do it smart enough :)

**Comment by joekinley** [comment]
Any news on this? Otherwise i need to keep the hack in my code
